import { useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, BrainCircuit, ChevronRight, Database, FileArchive, FileText, Gauge, Home, Layers3, Map, Radar, ShieldCheck, UploadCloud } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from './components/ui/card'
import { Button } from './components/ui/button'
import { Badge } from './components/ui/badge'
import { Tabs } from './components/ui/tabs'

const nav = [
  ['Dashboard', Home], ['Case Management', FileArchive], ['Evidence Management', Database], ['Visual Analysis (CNN)', BrainCircuit],
  ['Telemetry Analysis (LSTM)', Activity], ['Fusion Analysis', Layers3], ['Explainable AI', Radar], ['Reporting', FileText]
]
const cases = [
  ['UAV-DFI-2026-014', 'Restricted Airspace Incursion', 'Dr. Maya Chen', 'Active', '2026-06-04'],
  ['UAV-DFI-2026-011', 'Stadium Surveillance Breach', 'James Okafor', 'Review', '2026-05-28'],
  ['UAV-DFI-2026-008', 'Cargo Yard Reconnaissance', 'Elena Rossi', 'Closed', '2026-05-17'],
  ['UAV-DFI-2026-006', 'Airport Perimeter Flyover', 'Dr. Aaron Patel', 'Active', '2026-05-09']
]
const evidence = [
  ['IMG_2034_THERMAL.jpg', 'Thermal Image', '7f4a9b...c18e92', 'Verified'],
  ['flightlog_0614.csv', 'Telemetry Log', 'c91d0e...44aa71', 'Verified'],
  ['controller_dump.bin', 'Firmware Dump', '9aa40c...e7f210', 'Pending'],
  ['payload_video.mp4', 'Optical Video', '1d91ab...090bd1', 'Verified']
]
const perf = [{name:'CNN', acc:96.8, f1:94.9},{name:'LSTM', acc:93.4, f1:91.2},{name:'Fusion', acc:98.1, f1:97.4}]
const timeline = [{t:'00:00', alt:40, anomaly:12},{t:'02:00', alt:88, anomaly:18},{t:'04:00', alt:132, anomaly:41},{t:'06:00', alt:121, anomaly:84},{t:'08:00', alt:64, anomaly:36}]

function Shell({ page, setPage }) { return <aside className="fixed inset-y-0 left-0 z-20 hidden w-72 border-r border-slate-800 bg-slate-950/95 p-5 lg:block">
  <div className="mb-8 flex items-center gap-3"><div className="rounded-xl bg-sky-500/20 p-3 text-sky-300"><ShieldCheck/></div><div><h1 className="font-bold text-slate-50">UAV-DFI Lab</h1><p className="text-xs text-slate-400">Forensic Investigation Platform</p></div></div>
  <nav className="space-y-2">{nav.map(([n, Icon]) => <button key={n} onClick={()=>setPage(n)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${page===n?'bg-sky-500/15 text-sky-200 ring-1 ring-sky-400/40':'text-slate-400 hover:bg-slate-900 hover:text-slate-100'}`}><Icon size={18}/><span>{n}</span><ChevronRight className="ml-auto" size={15}/></button>)}</nav>
  <div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-sky-500/20 bg-sky-500/10 p-4"><p className="text-xs uppercase text-sky-300">Chain of custody</p><p className="mt-1 text-sm text-slate-200">Integrity monitor active</p></div>
</aside> }
function Stat({ label, value, sub, tone='sky' }) { return <Card><CardContent><p className="text-sm text-slate-400">{label}</p><div className="mt-2 flex items-end justify-between"><h2 className="text-3xl font-bold text-slate-50">{value}</h2><Badge tone={tone}>{sub}</Badge></div></CardContent></Card> }
function DataTable({ headers, rows, actions=false }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr>{headers.map(h=><th className="border-b border-slate-800 px-3 py-3" key={h}>{h}</th>)}{actions&&<th className="border-b border-slate-800 px-3 py-3">Actions</th>}</tr></thead><tbody>{rows.map((r,i)=><tr className="text-slate-200" key={i}>{r.map((c,j)=><td className="border-b border-slate-800/70 px-3 py-3" key={j}>{j===3?<Badge tone={c==='Closed'||c==='Verified'?'emerald':c==='Pending'?'amber':'sky'}>{c}</Badge>:c}</td>)}{actions&&<td className="space-x-2 border-b border-slate-800/70 px-3 py-3"><Button size="sm" variant="outline">View</Button><Button size="sm" variant="ghost">Edit</Button><Button size="sm" variant="destructive">Close Case</Button></td>}</tr>)}</tbody></table></div> }

function Dashboard(){return <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6"><Stat label="Total Cases" value="42" sub="+6 month"/><Stat label="Evidence Files" value="1,284" sub="3.8 TB"/><Stat label="CNN Accuracy" value="96.8%" sub="ResNet-50"/><Stat label="LSTM Accuracy" value="93.4%" sub="sequence"/><Stat label="Fusion Accuracy" value="98.1%" sub="validated"/><Stat label="System Status" value="Online" sub="secure" tone="emerald"/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Recent Cases</CardTitle></CardHeader><CardContent><DataTable headers={['Case ID','Case Name','Investigator','Status','Date Created']} rows={cases}/></CardContent></Card><Card><CardHeader><CardTitle>Model Performance</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer><BarChart data={perf}><CartesianGrid stroke="#1e293b"/><XAxis dataKey="name" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip contentStyle={{background:'#0f172a',border:'1px solid #334155'}}/><Bar dataKey="acc" fill="#38bdf8" radius={[8,8,0,0]}/><Bar dataKey="f1" fill="#64748b" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></CardContent></Card></div></>}
function CaseManagement(){return <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Case Management</CardTitle><Button>Create Case</Button></CardHeader><CardContent><DataTable headers={['Case ID','Case Name','Investigator','Status','Date Created']} rows={cases} actions/></CardContent></Card>}
function EvidenceManagement(){return <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader className="flex-row justify-between"><CardTitle>Evidence Repository</CardTitle><Button><UploadCloud size={16}/>Upload Evidence</Button></CardHeader><CardContent><DataTable headers={['File Name','Evidence Type','SHA256 Hash','Verification Status']} rows={evidence}/></CardContent></Card><Card><CardHeader><CardTitle>File Preview</CardTitle></CardHeader><CardContent><div className="rounded-xl border border-dashed border-sky-500/40 bg-slate-950 p-6 text-center"><Database className="mx-auto text-sky-300" size={56}/><h3 className="mt-4 font-semibold">flightlog_0614.csv</h3><p className="mt-2 text-sm text-slate-400">GPS, IMU, altitude and controller event stream. SHA256 verified and chain-of-custody locked.</p></div></CardContent></Card></div>}
function Visual(){return <div className="grid gap-6 xl:grid-cols-2"><Upload title="Image Upload" desc="Drop optical, thermal, or multispectral UAV imagery"/><Card><CardHeader><CardTitle>Prediction Result</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold text-sky-200">Unauthorized Perimeter Reconnaissance</p><p className="mt-2 text-slate-400">Confidence Score: 96.8%</p><Heat title="Grad-CAM Visualization"/><Button className="mt-5">Run Analysis</Button></CardContent></Card></div>}
function Telemetry(){return <div className="grid gap-6 xl:grid-cols-2"><Upload title="Telemetry File Upload" desc="CSV, JSON, GPX flight logs and controller exports"/><Card><CardHeader><CardTitle>Behaviour Classification</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold text-sky-200">Loitering + No-Fly Zone Approach</p><p className="mt-2 text-slate-400">Anomaly Score: 0.84</p><div className="mt-4 h-52"><ResponsiveContainer><LineChart data={timeline}><XAxis dataKey="t" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip contentStyle={{background:'#0f172a',border:'1px solid #334155'}}/><Line dataKey="alt" stroke="#38bdf8"/><Line dataKey="anomaly" stroke="#fb7185"/></LineChart></ResponsiveContainer></div><p className="text-sm text-slate-400">GPS Route Visualization: 37.618°N, 122.375°W perimeter arc. Flight Timeline includes altitude and anomaly overlays.</p><Button className="mt-5">Run Analysis</Button></CardContent></Card></div>}
function Fusion(){return <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Fusion Summary Card</CardTitle></CardHeader><CardContent className="space-y-4"><Stat label="CNN Result" value="Recon" sub="96.8%"/><Stat label="LSTM Result" value="Loiter" sub="0.84"/><Stat label="Correlation Score" value="0.91" sub="high"/><Stat label="Final Risk Assessment" value="Severe" sub="escalate" tone="rose"/></CardContent></Card><Card><CardHeader><CardTitle>Risk Gauge</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer><PieChart><Pie data={[{name:'Risk',value:86},{name:'Residual',value:14}]} innerRadius={80} outerRadius={120} startAngle={180} endAngle={0} dataKey="value"><Cell fill="#fb7185"/><Cell fill="#1e293b"/></Pie></PieChart></ResponsiveContainer><p className="text-center text-3xl font-bold text-rose-300">86 / 100</p></CardContent></Card></div>}
function Explainable(){const [tab,setTab]=useState('Grad-CAM');return <Card><CardHeader><CardTitle>Explainable AI</CardTitle></CardHeader><CardContent><Tabs tabs={['Grad-CAM','SHAP','LIME']} active={tab} onChange={setTab}/><div className="mt-6 grid gap-6 md:grid-cols-3"><Heat title={`${tab} Heatmaps`}/><Panel title="Feature Importance" text="Altitude deviation, waypoint dwell time, restricted-zone bearing, thermal payload signature."/><Panel title="Local Explanations" text="Decision attributed to repeated elliptical passes near perimeter sensors and abnormal yaw corrections."/></div></CardContent></Card>}
function Reporting(){return <Card><CardHeader className="flex-row justify-between"><CardTitle>Generated Reports</CardTitle><div className="flex gap-2"><Button>Export PDF</Button><Button variant="outline">Export CSV</Button><Button variant="outline">Export JSON</Button></div></CardHeader><CardContent><DataTable headers={['Report ID','Case','Type','Status','Generated']} rows={[[ 'RPT-014-A','Restricted Airspace Incursion','Fusion Forensic Brief','Verified','2026-06-14'],['RPT-011-X','Stadium Surveillance Breach','XAI Appendix','Draft','2026-06-02']]}/></CardContent></Card>}
function Upload({title,desc}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><div className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-600 bg-slate-950/60 p-8 text-center"><UploadCloud className="text-sky-300" size={64}/><h3 className="mt-5 text-xl font-semibold">Secure forensic upload</h3><p className="mt-2 max-w-sm text-slate-400">{desc}. Mock acquisition preserves hash, timestamp, and investigator notes.</p></div></CardContent></Card>}
function Heat({title}){return <div className="mt-4 rounded-2xl border border-slate-700 bg-[radial-gradient(circle_at_30%_30%,rgba(56,189,248,.55),transparent_22%),radial-gradient(circle_at_70%_55%,rgba(244,63,94,.55),transparent_18%),linear-gradient(135deg,#0f172a,#1e293b)] p-5"><Map className="text-slate-200"/><p className="mt-24 font-semibold text-slate-100">{title}</p></div>}
function Panel({title,text}){return <div className="rounded-2xl border border-slate-700 bg-slate-950/60 p-5"><Gauge className="text-sky-300"/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-400">{text}</p></div>}
export default function App(){const [page,setPage]=useState('Dashboard'); const pages={'Dashboard':<Dashboard/>,'Case Management':<CaseManagement/>,'Evidence Management':<EvidenceManagement/>,'Visual Analysis (CNN)':<Visual/>,'Telemetry Analysis (LSTM)':<Telemetry/>,'Fusion Analysis':<Fusion/>,'Explainable AI':<Explainable/>,'Reporting':<Reporting/>}; return <div className="min-h-screen bg-[linear-gradient(135deg,#07111f,#0f172a_45%,#111827)] text-slate-100"><Shell page={page} setPage={setPage}/><main className="lg:pl-72"><div className="sticky top-0 z-10 border-b border-slate-800 bg-slate-950/80 p-4 backdrop-blur lg:hidden"><select className="w-full rounded-lg bg-slate-900 p-3" value={page} onChange={e=>setPage(e.target.value)}>{nav.map(([n])=><option key={n}>{n}</option>)}</select></div><section className="mx-auto max-w-7xl p-4 md:p-8"><div className="mb-8"><p className="text-sm uppercase tracking-[0.35em] text-sky-300">Research Prototype</p><h2 className="mt-2 text-3xl font-bold md:text-5xl">{page}</h2><p className="mt-3 max-w-3xl text-slate-400">Blue-grey cybersecurity workspace for UAV digital forensic acquisition, AI analysis, explainability, and evidentiary reporting.</p></div>{pages[page]}</section></main></div>}
